### PR TITLE
Create Matrix Function

### PR DESCRIPTION
**Pull request by Ross117**
I have created a new file in the utils folder which contains a create matrix function. The function returns a 2D array of randomised boolean values. The size of the returned array is determined by the arguments passed to the function, but the rows and columns must both be between 10 to 100.

### CODE REVIEW

**Comment by anthonytranDev** [comment]
Ross please can you name the branch "GL-002", push the code up, then test your code out in an isolated environment, via a fresh install - i.e. git clone of the project before making any pull requests

For more details - "How to fulfil a ticket" -https://docs.google.com/document/d/1kQXPm2lH2cXeRI8C9pkS9JFA64owsOwjps19XlLaTLc/edit#heading=h.b82rg4gtd31v

Oh and remove this "Pull Request" - as steps taken here. Does not follow the set of guidelines mentioned in the document above. Thanks.  :)

**Comment by Sandbagger** [comment]
Ross, 

Am I being daft? I cloned your repo in order to review your changes, and used "git branch -a" to list all the remote branches, but I can't see your writeCreateMatrixFunction. Am I missing something?

Will

**Comment by Ross117** [comment]
Hey Will, not completely sure. Does the branch exist on your local machine? This is a documentation page about git clone 
https://www.git-scm.com/docs/git-clone

**Comment by Ross117** [comment]
Pull request closed due to issues with branch naming convention and the testing of the code.

**Pull request closed without merging**
